apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      slack_api_url: 'SLACK_WEBHOOK_URL'
    
    route:
      group_by: ['alertname']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 1h
      receiver: 'slack-notifications'
      routes:
        - match:
            severity: critical
          receiver: 'oncall-engineer'
          continue: true
    
    receivers:
      - name: 'slack-notifications'
        slack_configs:
          - channel: '#alerts'
            title: '🚨 Alert: {{ .GroupLabels.alertname }}'
            text: |
              *Alert:* {{ .GroupLabels.alertname }}
              *Severity:* {{ .CommonLabels.severity }}
              *Description:* {{ .CommonAnnotations.description }}
              *Instance:* {{ .CommonLabels.instance }}
              *Started:* {{ .StartsAt | since }}
      
      - name: 'oncall-engineer'
        slack_configs:
          - channel: '#oncall'
            title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
            text: |
              *CRITICAL ALERT - ONCALL ENGINEER NEEDED*
              *Alert:* {{ .GroupLabels.alertname }}
              *Severity:* {{ .CommonLabels.severity }}
              *Description:* {{ .CommonAnnotations.description }}
              *Instance:* {{ .CommonLabels.instance }}
              *Started:* {{ .StartsAt | since }} 