apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: production-alerts
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
  - name: application.alerts
    rules:
    # High CPU Usage
    - alert: HighCPUUsage
      expr: container_cpu_usage_seconds_total > 0.8
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "High CPU usage detected"
        description: "Container {{ $labels.container }} has high CPU usage ({{ $value }}%)"
        runbook_url: "https://wiki.company.com/runbooks/high-cpu-usage"
    
    # High Memory Usage
    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes / container_spec_memory_limit_bytes > 0.85
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "High memory usage detected"
        description: "Container {{ $labels.container }} has high memory usage ({{ $value | humanizePercentage }})"
        runbook_url: "https://wiki.company.com/runbooks/high-memory-usage"
    
    # Pod CrashLoopBackOff
    - alert: PodCrashLoopBackOff
      expr: kube_pod_status_phase{phase="Running"} == 0 and kube_pod_status_phase{phase="Failed"} > 0
      for: 2m
      labels:
        severity: critical
        team: oncall
      annotations:
        summary: "Pod is in CrashLoopBackOff state"
        description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is crashing repeatedly"
        runbook_url: "https://wiki.company.com/runbooks/pod-crashloop"
    
    # Service Down
    - alert: ServiceDown
      expr: up == 0
      for: 1m
      labels:
        severity: critical
        team: oncall
      annotations:
        summary: "Service is down"
        description: "Service {{ $labels.job }} is not responding"
        runbook_url: "https://wiki.company.com/runbooks/service-down"
    
    # High Error Rate
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
      for: 3m
      labels:
        severity: critical
        team: oncall
      annotations:
        summary: "High error rate detected"
        description: "Error rate is {{ $value | humanizePercentage }} (threshold: 5%)"
        runbook_url: "https://wiki.company.com/runbooks/high-error-rate"
    
    # Slow Response Time
    - alert: SlowResponseTime
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Slow response time detected"
        description: "95th percentile response time is {{ $value }}s (threshold: 2s)"
        runbook_url: "https://wiki.company.com/runbooks/slow-response-time"
    
    # Disk Space Low
    - alert: DiskSpaceLow
      expr: (node_filesystem_size_bytes - node_filesystem_free_bytes) / node_filesystem_size_bytes > 0.85
      for: 5m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "Disk space is running low"
        description: "Disk usage is {{ $value | humanizePercentage }} (threshold: 85%)"
        runbook_url: "https://wiki.company.com/runbooks/disk-space-low"
    
    # Node Down
    - alert: NodeDown
      expr: up == 0
      for: 5m
      labels:
        severity: critical
        team: oncall
      annotations:
        summary: "Node is down"
        description: "Node {{ $labels.instance }} is not responding"
        runbook_url: "https://wiki.company.com/runbooks/node-down"
    
    # High Network Errors
    - alert: HighNetworkErrors
      expr: rate(container_network_receive_errors_total[5m]) > 0
      for: 2m
      labels:
        severity: warning
        team: devops
      annotations:
        summary: "High network errors detected"
        description: "Network errors are occurring on {{ $labels.instance }}"
        runbook_url: "https://wiki.company.com/runbooks/network-errors" 