apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: slack-config
  namespace: monitoring
spec:
  route:
    receiver: 'slack-general'
    groupBy: ['alertname', 'namespace']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    routes:
    - match:
        severity: critical
      receiver: 'slack-oncall'
      continue: true
    - match:
        severity: warning
      receiver: 'slack-general'
      continue: true
  
  receivers:
  - name: 'slack-general'
    slackConfigs:
    - channel: '#devops-alerts'
      title: '🚨 Alert: {{ .GroupLabels.alertname }}'
      text: |
        *Alert:* {{ .GroupLabels.alertname }}
        *Severity:* {{ .CommonLabels.severity }}
        *Namespace:* {{ .GroupLabels.namespace }}
        *Description:* {{ .CommonAnnotations.summary }}
        *Details:* {{ .CommonAnnotations.description }}
        *Runbook:* {{ .CommonAnnotations.runbook_url }}
        
        {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Status:* {{ .Status }}
        *Started:* {{ .StartsAt | since }}
        {{ end }}
  
  - name: 'slack-oncall'
    slackConfigs:
    - channel: '#oncall-emergency'
      title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
      text: |
        *CRITICAL ALERT*
        *Alert:* {{ .GroupLabels.alertname }}
        *Severity:* {{ .CommonLabels.severity }}
        *Namespace:* {{ .GroupLabels.namespace }}
        *Description:* {{ .CommonAnnotations.summary }}
        *Details:* {{ .CommonAnnotations.description }}
        *Runbook:* {{ .CommonAnnotations.runbook_url }}
        
        {{ range .Alerts }}
        *Alert:* {{ .Annotations.summary }}
        *Status:* {{ .Status }}
        *Started:* {{ .StartsAt | since }}
        {{ end }}
  
  - name: 'null'
  
  inhibitRules:
  - equal: ['namespace', 'alertname']
    sourceMatchers:
    - severity = critical
    targetMatchers:
    - severity =~ warning|info
  - equal: ['namespace', 'alertname']
    sourceMatchers:
    - severity = warning
    targetMatchers:
    - severity = info 