apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      slack_api_url: 'https://hooks.slack.com/services/YOUR_WEBHOOK_URL'  # Replace with your Slack webhook URL
    
    route:
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'slack-general'
      routes:
      - match:
          severity: critical
        receiver: 'slack-oncall'
        continue: true
      - match:
          severity: warning
        receiver: 'slack-general'
        continue: true
    
    receivers:
    - name: 'slack-general'
      slack_configs:
      - channel: '#devops-alerts'
        title: '🚨 Alert: {{ .GroupLabels.alertname }}'
        text: |
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Namespace:* {{ .GroupLabels.namespace }}
          *Description:* {{ .CommonAnnotations.summary }}
          *Details:* {{ .CommonAnnotations.description }}
          *Runbook:* {{ .CommonAnnotations.runbook_url }}
          
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Status:* {{ .Status }}
          *Started:* {{ .StartsAt | since }}
          {{ end }}
    
    - name: 'slack-oncall'
      slack_configs:
      - channel: '#oncall-emergency'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          *CRITICAL ALERT*
          *Alert:* {{ .GroupLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Namespace:* {{ .GroupLabels.namespace }}
          *Description:* {{ .CommonAnnotations.summary }}
          *Details:* {{ .CommonAnnotations.description }}
          *Runbook:* {{ .CommonAnnotations.runbook_url }}
          
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Status:* {{ .Status }}
          *Started:* {{ .StartsAt | since }}
          {{ end }}
    
    - name: 'null'
    
    inhibit_rules:
    - equal: ['namespace', 'alertname']
      source_matchers:
      - severity = critical
      target_matchers:
      - severity =~ warning|info
    - equal: ['namespace', 'alertname']
      source_matchers:
      - severity = warning
      target_matchers:
      - severity = info 