apiVersion: v1
kind: Secret
metadata:
  name: slack-webhook-url
  namespace: monitoring
type: Opaque
stringData:
  url: "https://hooks.slack.com/services/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" 