# values.yaml

replicaCount: 3

image:
  repository: your-dockerhub-username/your-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

env:
  - name: NODE_ENV
    value: production

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: your-app.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Add more sections as needed for your app!
