{{- if .Values.prometheusRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "monitoring-config.fullname" . }}-rules
  namespace: {{ .Values.monitoring.namespace }}
  labels:
    release: prometheus
spec:
  groups:
  {{- range .Values.prometheusRules.rules }}
  - name: {{ .name }}
    rules:
    {{- range .groups }}
    {{- range .rules }}
    - alert: {{ .alert }}
      expr: {{ .expr }}
      for: {{ .for }}
      labels:
        {{- toYaml .labels | nindent 8 }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
    {{- end }}
  {{- end }}
{{- end }} 