apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anupsharma329/full-ArgoCD-task.git
    targetRevision: HEAD
    path: backend-chart
    helm:
      values: |
        replicaCount: 3
        image:
          repository: anupsharma329/backend
          tag: "v1.1"
        service:
          type: ClusterIP
          port: 4000
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
          NODE_ENV: "production"
          PORT: "4000"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 