apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-helm
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anupsharma329/full-ArgoCD-task.git
    targetRevision: HEAD
    path: frontend-chart
    helm:
      values: |
        replicaCount: 3
        image:
          repository: anupsharma329/frontend
          tag: "v1.0.7"
        service:
          type: ClusterIP
          port: 80
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
          NODE_ENV: "production"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 