apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ssl-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/anupsharma329/full-ArgoCD-task.git
    targetRevision: HEAD
    path: ssl-config
    helm:
      values: |
        domain: your-actual-domain.com  # Replace with your actual domain
        email: your-email@example.com  # Replace with your email
        ssl:
          enabled: true
          issuer: letsencrypt-prod
          secretName: ssl-tls-secret
        ingress:
          enabled: true
          className: nginx
          annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/ssl-redirect: "true"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        services:
          frontend:
            name: frontend-helm
            port: 80
            path: /
          backend:
            name: backend-helm
            port: 4000
            path: /api
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 